- include: docker.yml
  tags: docker

- include: server.yml
  tags: server

- include: rook.yml
  tags: rook
  delegate_to: 127.0.0.1
  connection: local
  when: install_rook

- include: certmanager_catalog.yml
  tags: certmanager
  when: install_certmanager
